//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Server
	{
		//ServiceHost host;

		public Server ()
		{
			/*host = new ServiceHost(typeof(SimulationUpdater), 
			                       new Uri[]{new Uri("net.pipe://localhost")});

			host.AddServiceEndpoint(typeof(SimulationUpdater),
			                        new BasicHttpBinding(),
			                        "Reverse");*/

			/*host.AddServiceEndpoint(typeof(SimulationUpdater),
			                        new NetNamedPipeBinding(),
			                        "PipeReverse");

			host.Open();*/
		}

		public void Close() {
			//this.host.Close();
		}
	}
}

